export const BROWSER_BRIDGE_PORT = 17399;

export type GsmtcSnapshot = {
  version: number;
  sessions: MediaSessionDto[];
  browserTabs?: BrowserTabMediaDto[];
};

export type BrowserTabMediaDto = {
  tabId: number;
  /** Stable UUID per browser profile, generated by the extension. */
  browserId: string;
  url: string;
  title: string;
  artist: string;
  album: string;
  playbackState: string;
  /** Best-effort cover image from MediaSession artwork or video poster */
  artworkUrl?: string;
};

export type MediaSessionDto = {
  /** Matches `GetSessions()` order for this snapshot. */
  sessionIndex: number;
  sourceAppUserModelId: string;
  title: string;
  artist: string;
  album: string;
  subtitle: string;
  playbackStatus: string;
  playbackType: string | null;
  timeline: TimelineDto;
  controls: ControlsDto;
  thumbnailMime: string | null;
  thumbnailBase64: string | null;
};

export type TimelineDto = {
  startTicks: number;
  endTicks: number;
  positionTicks: number;
  minSeekTicks: number;
  maxSeekTicks: number;
  lastUpdatedUnixMs: number;
};

export type ControlsDto = {
  playPauseToggleEnabled: boolean;
  nextEnabled: boolean;
  previousEnabled: boolean;
};
