use std::collections::HashMap;

use serde::{Deserialize, Serialize};

pub const SNAPSHOT_VERSION: u32 = 7;

/// Per-tab media reported by the PilPod Chromium companion extension (localhost HTTP).
/// Windows GSMTC often collapses all browser tabs into one session; this fills the gap.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BrowserTabMediaDto {
    pub tab_id: i32,
    /// Stable UUID generated by the extension and stored in chrome.storage.local.
    /// Lets the backend keep Chrome and Opera (or any two browsers) in separate slots.
    #[serde(default)]
    pub browser_id: String,
    #[serde(default)]
    pub url: String,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub artist: String,
    #[serde(default)]
    pub album: String,
    #[serde(default)]
    pub playback_state: String,
    #[serde(default)]
    pub artwork_url: String,
    /// Playback length in seconds (0 if unknown).
    #[serde(default)]
    pub duration: f64,
    /// Current position in seconds (0 if unknown).
    #[serde(default)]
    pub current_time: f64,
    /// Human-readable browser (injected from extension POST body; e.g. "Brave", "Chrome").
    #[serde(default)]
    pub browser_name: String,
    /// Last reported connection health for this browser slot (`connected` / `disconnected`).
    #[serde(default)]
    pub connection_state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AudioSessionInfoDto {
    pub instance_id: String,
    pub volume: f32,
    pub muted: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineDto {
    pub start_ticks: i64,
    pub end_ticks: i64,
    pub position_ticks: i64,
    pub min_seek_ticks: i64,
    pub max_seek_ticks: i64,
    pub last_updated_unix_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ControlsDto {
    pub play_pause_toggle_enabled: bool,
    pub next_enabled: bool,
    pub previous_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaSessionDto {
    /// Index in `GlobalSystemMediaTransportControlsSessionManager::GetSessions()` order.
    pub session_index: u32,
    pub source_app_user_model_id: String,
    pub title: String,
    pub artist: String,
    pub album: String,
    pub subtitle: String,
    pub playback_status: String,
    pub playback_type: Option<String>,
    pub timeline: TimelineDto,
    pub controls: ControlsDto,
    pub thumbnail_mime: Option<String>,
    pub thumbnail_base64: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio: Option<AudioSessionInfoDto>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GsmtcSnapshot {
    pub version: u32,
    pub sessions: Vec<MediaSessionDto>,
    #[serde(default)]
    pub browser_tabs: Vec<BrowserTabMediaDto>,
    /// Per Chromium profile (`browser_id`) — matched from WASAPI session display names.
    #[serde(default)]
    pub browser_audio: HashMap<String, AudioSessionInfoDto>,
}
