use serde::{Deserialize, Serialize};

pub const SNAPSHOT_VERSION: u32 = 3;

/// Per-tab media reported by the OmniMedia Chromium companion extension (localhost HTTP).
/// Windows GSMTC often collapses all browser tabs into one session; this fills the gap.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BrowserTabMediaDto {
    pub tab_id: i32,
    /// Stable UUID generated by the extension and stored in chrome.storage.local.
    /// Lets the backend keep Chrome and Opera (or any two browsers) in separate slots.
    #[serde(default)]
    pub browser_id: String,
    #[serde(default)]
    pub url: String,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub artist: String,
    #[serde(default)]
    pub album: String,
    #[serde(default)]
    pub playback_state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GsmtcSnapshot {
    pub version: u32,
    pub sessions: Vec<MediaSessionDto>,
    #[serde(default)]
    pub browser_tabs: Vec<BrowserTabMediaDto>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaSessionDto {
    /// Index in `GlobalSystemMediaTransportControlsSessionManager::GetSessions()` order.
    pub session_index: u32,
    pub source_app_user_model_id: String,
    pub title: String,
    pub artist: String,
    pub album: String,
    pub subtitle: String,
    pub playback_status: String,
    pub playback_type: Option<String>,
    pub timeline: TimelineDto,
    pub controls: ControlsDto,
    pub thumbnail_mime: Option<String>,
    pub thumbnail_base64: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineDto {
    pub start_ticks: i64,
    pub end_ticks: i64,
    pub position_ticks: i64,
    pub min_seek_ticks: i64,
    pub max_seek_ticks: i64,
    pub last_updated_unix_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ControlsDto {
    pub play_pause_toggle_enabled: bool,
    pub next_enabled: bool,
    pub previous_enabled: bool,
}
