//! Per-browser tab slots and command queue shared by the browser detector and
//! the localhost HTTP bridge.

use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
    time::Instant,
};

use serde::Serialize;

use crate::gsmtc::dto::BrowserTab;

/// Latest tab state pushed by one browser profile (keyed by `browserId` UUID).
#[derive(Debug, Clone)]
pub struct BrowserSlot {
    pub last_seen: Instant,
    /// Stable UUID generated by the extension and stored in `chrome.storage.local`.
    pub browser_id: String,
    /// Human-readable browser name sent by the extension (e.g. "Chrome", "Brave").
    pub browser_name: String,
    /// All open tabs in this browser — each with an optional `media` field.
    pub tabs: Vec<BrowserTab>,
}

/// Key: `browserId` UUID sent by the extension.
pub type BrowserSlotsMap = Arc<Mutex<HashMap<String, BrowserSlot>>>;

/// Commands the desktop app queues for a browser profile; the companion extension
/// receives them in the JSON body of its next POST to `/browser-tabs`.
pub type BrowserCommandsQueue = Arc<Mutex<HashMap<String, Vec<BrowserMediaCommand>>>>;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BrowserMediaCommand {
    pub tab_id: i32,
    /// `playPause`, `next`, `previous`, `focusTab`, `reactivateTab`, `reloadTab`, or `closeTab`
    pub action: String,
    /// Timestamp of when the command was enqueued; used to drop stale entries.
    #[serde(skip)]
    pub enqueued_at: Instant,
}

pub fn enqueue_browser_command(
    queue: &BrowserCommandsQueue,
    browser_id: &str,
    tab_id: i32,
    action: &str,
) {
    if let Ok(mut q) = queue.lock() {
        q.entry(browser_id.to_string())
            .or_default()
            .push(BrowserMediaCommand {
                tab_id,
                action: action.to_string(),
                enqueued_at: Instant::now(),
            });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enqueue_orders_per_browser() {
        let q: BrowserCommandsQueue = Arc::new(Mutex::new(HashMap::new()));
        enqueue_browser_command(&q, "b1", 10, "next");
        enqueue_browser_command(&q, "b1", 11, "previous");
        enqueue_browser_command(&q, "b2", 20, "playPause");
        let g = q.lock().expect("lock");
        assert_eq!(g["b1"].len(), 2);
        assert_eq!(g["b1"][0].tab_id, 10);
        assert_eq!(g["b1"][1].action, "previous");
        assert_eq!(g["b2"][0].tab_id, 20);
    }
}
